---
title: "NFL_Project"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading in data

```{r Loading_packages, message=FALSE}
library(tidyverse)
library(janitor)
library(moderndive)
```


```{r Reading_Files, message=FALSE, warning=FALSE}
NFL <- read_csv(here::here("Data", "pbp-2021.csv")) %>% 
  clean_names() %>%
  select(-`x11`,-`x13`,-`x17`,-`x18`)

```



```{r Frequency_Table_PlayType_by_down}
 play_down_freq <- NFL %>% 
  count(play_type,down)
play_down_freq
```
```{r Chart of play type and down}

ggplot( data=play_down_freq, aes(x=down, y=play_type, size=n) ) +
geom_point( )

NFL %>% filter(is.na(play_type))
```

```{r Changing NA Wildcat plays}
#Specifying the data set
#filter by description and play type
#play type must contain NA and Description must contain DIRECT SNAP
#mutate/case to do if else statement, Denny's activity Example.
#Chapter 14, Stringer commands, Week 5 Wednesdays class
NFL %>% mutate(play_type=case_when(is.na(play_type) & str_detect(description,"DIRECT SNAP")~ "WILDCAT",
                                   TRUE~play_type))



```







```{r Penalty Yards for Chicago Bears}
#Want to first compute the Average of the league and then compare it to the Chicago Bears.
#(DONE Removed all plays with 0 penalty yards), so the league average was computed and then we filter it to only include the Chicago Bears

  
LA_Penalty <- NFL %>% 
  filter(!penalty_yards==0) %>% 
  summarise(LA_mean=mean(penalty_yards))
Penaltys_team <- NFL %>% 
  count(offense_team,penalty_yards) %>% filter(offense_team=="CHI", !penalty_yards==0)
  Penaltys_team
  ggplot( data=Penaltys_team, aes(x=offense_team, y=penalty_yards, size=n) ) +
geom_point(alpha=.5) + geom_hline(yintercept = 8.62)

  Penaltys_team

```

```{r Play Type Yardage}
Playtype_Yardage <- NFL %>% filter(!play_type%in%c("TIMEOUT","CLOCK STOP", "EXCEPTION", "PENALTY","KICK OFF","EXTRA POINT", "QB KNEEL", "NO PLAY", "FIELD GOAL","PUNT","TWO-POINT CONVERSION",NA,"FUMBLES")) %>%  
  count(yards, play_type)
Playtype_Yardage
ggplot( data=Playtype_Yardage, aes(x=play_type, y=yards, size=n) ) +
geom_point(alpha=.5 )
#Removed variables in graph that cannot report gains of yards, sacks can only result in negative yards, otherwise it is considered a scramble. The rest of chart is showing the frequency of plays and what amount of yards they result in.
```
```{r probability}
NFL %>% 
  group_by(down,is_touchdown) %>% 
  summarise(n=n()) %>% 
  mutate(prob=n/sum(n))
```


``` {r Resample + Function}
set.seed(2000)
NFL_CHI_boots <- NFL %>% filter(offense_team=="CHI", down == 4) %>% 
  rep_sample_n(size= nrow(.), reps=1000, replace = TRUE) %>% 
  group_by(down,is_touchdown) %>% 
  summarise(n=n()) %>% 
  mutate(prob=n/sum(n))




  

```






















